# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\study\github\stockTushare\UI\mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1205)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setMinimumSize(QtCore.QSize(380, 0))
        self.tableView.setBaseSize(QtCore.QSize(380, 0))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.pushDailyButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushDailyButton.setObjectName("pushDailyButton")
        self.verticalLayout.addWidget(self.pushDailyButton)
        self.pushDailyBasicButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushDailyBasicButton.setObjectName("pushDailyBasicButton")
        self.verticalLayout.addWidget(self.pushDailyBasicButton)
        self.pushStockBasicButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushStockBasicButton.setObjectName("pushStockBasicButton")
        self.verticalLayout.addWidget(self.pushStockBasicButton)
        self.pushCompanyButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushCompanyButton.setObjectName("pushCompanyButton")
        self.verticalLayout.addWidget(self.pushCompanyButton)
        self.pushToplistButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushToplistButton.setObjectName("pushToplistButton")
        self.verticalLayout.addWidget(self.pushToplistButton)
        self.pushTopInstButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushTopInstButton.setObjectName("pushTopInstButton")
        self.verticalLayout.addWidget(self.pushTopInstButton)
        self.pushBlockTradeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushBlockTradeButton.setFlat(False)
        self.pushBlockTradeButton.setObjectName("pushBlockTradeButton")
        self.verticalLayout.addWidget(self.pushBlockTradeButton)
        self.pushButton_moneyflow = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_moneyflow.setFlat(False)
        self.pushButton_moneyflow.setObjectName("pushButton_moneyflow")
        self.verticalLayout.addWidget(self.pushButton_moneyflow)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 45))
        self.menubar.setObjectName("menubar")
        self.menu_query = QtWidgets.QMenu(self.menubar)
        self.menu_query.setObjectName("menu_query")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_ups_and_downs = QtWidgets.QAction(MainWindow)
        self.action_ups_and_downs.setObjectName("action_ups_and_downs")
        self.action_update_daily_info = QtWidgets.QAction(MainWindow)
        self.action_update_daily_info.setObjectName("action_update_daily_info")
        self.action_update_daily_basic_info = QtWidgets.QAction(MainWindow)
        self.action_update_daily_basic_info.setObjectName("action_update_daily_basic_info")
        self.action_update_top_list_info = QtWidgets.QAction(MainWindow)
        self.action_update_top_list_info.setObjectName("action_update_top_list_info")
        self.action_update_top_inst_info = QtWidgets.QAction(MainWindow)
        self.action_update_top_inst_info.setObjectName("action_update_top_inst_info")
        self.action_update_block_trade_info = QtWidgets.QAction(MainWindow)
        self.action_update_block_trade_info.setObjectName("action_update_block_trade_info")
        self.action_update_moneyflow_info = QtWidgets.QAction(MainWindow)
        self.action_update_moneyflow_info.setObjectName("action_update_moneyflow_info")
        self.action_update_all_info = QtWidgets.QAction(MainWindow)
        self.action_update_all_info.setObjectName("action_update_all_info")
        self.action_update_stock_basic_info = QtWidgets.QAction(MainWindow)
        self.action_update_stock_basic_info.setObjectName("action_update_stock_basic_info")
        self.action_update_company_info = QtWidgets.QAction(MainWindow)
        self.action_update_company_info.setObjectName("action_update_company_info")
        self.menu_query.addAction(self.action_ups_and_downs)
        self.menu.addAction(self.action_update_daily_info)
        self.menu.addAction(self.action_update_daily_basic_info)
        self.menu.addAction(self.action_update_top_list_info)
        self.menu.addAction(self.action_update_top_inst_info)
        self.menu.addAction(self.action_update_block_trade_info)
        self.menu.addAction(self.action_update_moneyflow_info)
        self.menu.addAction(self.action_update_stock_basic_info)
        self.menu.addAction(self.action_update_company_info)
        self.menu.addSeparator()
        self.menu.addAction(self.action_update_all_info)
        self.menubar.addAction(self.menu_query.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushDailyButton.setText(_translate("MainWindow", "查看选定日期股票交易信息"))
        self.pushDailyBasicButton.setText(_translate("MainWindow", "查看选定日期股票指标信息"))
        self.pushStockBasicButton.setText(_translate("MainWindow", "查看股票基本信息"))
        self.pushCompanyButton.setText(_translate("MainWindow", "查看公司基本信息"))
        self.pushToplistButton.setText(_translate("MainWindow", "查看龙虎榜信息"))
        self.pushTopInstButton.setText(_translate("MainWindow", "查看龙虎榜机构交易信息"))
        self.pushBlockTradeButton.setText(_translate("MainWindow", "查看大宗交易信息"))
        self.pushButton_moneyflow.setText(_translate("MainWindow", "查看个股资金流向信息"))
        self.menu_query.setTitle(_translate("MainWindow", "具体查询"))
        self.menu.setTitle(_translate("MainWindow", "数据更新"))
        self.action_ups_and_downs.setText(_translate("MainWindow", "涨跌查询"))
        self.action_ups_and_downs.setToolTip(_translate("MainWindow", "涨跌查询"))
        self.action_ups_and_downs.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.action_update_daily_info.setText(_translate("MainWindow", "更新每日交易信息"))
        self.action_update_daily_basic_info.setText(_translate("MainWindow", "更新每日指标信息"))
        self.action_update_top_list_info.setText(_translate("MainWindow", "更新龙虎榜信息"))
        self.action_update_top_inst_info.setText(_translate("MainWindow", "更新龙虎榜机构信息"))
        self.action_update_block_trade_info.setText(_translate("MainWindow", "更新大宗交易信息"))
        self.action_update_moneyflow_info.setText(_translate("MainWindow", "更新个股资金流向信息"))
        self.action_update_all_info.setText(_translate("MainWindow", "更新所有信息"))
        self.action_update_all_info.setToolTip(_translate("MainWindow", "更新所有信息"))
        self.action_update_stock_basic_info.setText(_translate("MainWindow", "更新股票基本信息"))
        self.action_update_company_info.setText(_translate("MainWindow", "更新上市公司信息"))

