# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2319, 1705)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.frame)
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.basicinfofarme = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicinfofarme.sizePolicy().hasHeightForWidth())
        self.basicinfofarme.setSizePolicy(sizePolicy)
        self.basicinfofarme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.basicinfofarme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.basicinfofarme.setObjectName("basicinfofarme")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.basicinfofarme)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.basicinfofarme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(500, 873))
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setSelectedDate(QtCore.QDate(2019, 3, 1))
        self.calendarWidget.setMinimumDate(QtCore.QDate(2011, 1, 1))
        self.calendarWidget.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.pushDailyButton = QtWidgets.QPushButton(self.basicinfofarme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDailyButton.sizePolicy().hasHeightForWidth())
        self.pushDailyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(11)
        self.pushDailyButton.setFont(font)
        self.pushDailyButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushDailyButton.setCheckable(False)
        self.pushDailyButton.setDefault(False)
        self.pushDailyButton.setFlat(False)
        self.pushDailyButton.setObjectName("pushDailyButton")
        self.verticalLayout.addWidget(self.pushDailyButton)
        self.pushDailyBasicButton = QtWidgets.QPushButton(self.basicinfofarme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDailyBasicButton.sizePolicy().hasHeightForWidth())
        self.pushDailyBasicButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(11)
        self.pushDailyBasicButton.setFont(font)
        self.pushDailyBasicButton.setObjectName("pushDailyBasicButton")
        self.verticalLayout.addWidget(self.pushDailyBasicButton)
        self.pushStockBasicButton = QtWidgets.QPushButton(self.basicinfofarme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushStockBasicButton.sizePolicy().hasHeightForWidth())
        self.pushStockBasicButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(11)
        self.pushStockBasicButton.setFont(font)
        self.pushStockBasicButton.setObjectName("pushStockBasicButton")
        self.verticalLayout.addWidget(self.pushStockBasicButton)
        self.pushCompanyButton = QtWidgets.QPushButton(self.basicinfofarme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCompanyButton.sizePolicy().hasHeightForWidth())
        self.pushCompanyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(11)
        self.pushCompanyButton.setFont(font)
        self.pushCompanyButton.setObjectName("pushCompanyButton")
        self.verticalLayout.addWidget(self.pushCompanyButton)
        self.horizontalLayout.addWidget(self.basicinfofarme)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(200, 0, 187, 57))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushDailyButton.setText(_translate("MainWindow", "查看选定日期股票交易信息"))
        self.pushDailyBasicButton.setText(_translate("MainWindow", "查看选定日期股票指标信息"))
        self.pushStockBasicButton.setText(_translate("MainWindow", "查看股票基本信息"))
        self.pushCompanyButton.setText(_translate("MainWindow", "查看公司基本信息"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

