# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\study\github\stockTushare\UI\upsdownsFm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpsAndDownsWindow(object):
    def setupUi(self, UpsAndDownsWindow):
        UpsAndDownsWindow.setObjectName("UpsAndDownsWindow")
        UpsAndDownsWindow.resize(1744, 1484)
        self.centralwidget = QtWidgets.QWidget(UpsAndDownsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_pct_chg = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pct_chg.sizePolicy().hasHeightForWidth())
        self.lineEdit_pct_chg.setSizePolicy(sizePolicy)
        self.lineEdit_pct_chg.setObjectName("lineEdit_pct_chg")
        self.gridLayout.addWidget(self.lineEdit_pct_chg, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vol.sizePolicy().hasHeightForWidth())
        self.lineEdit_vol.setSizePolicy(sizePolicy)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.gridLayout.addWidget(self.lineEdit_vol, 5, 2, 1, 1)
        self.comboBox_pct_chg = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pct_chg.sizePolicy().hasHeightForWidth())
        self.comboBox_pct_chg.setSizePolicy(sizePolicy)
        self.comboBox_pct_chg.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_pct_chg.setEditable(True)
        self.comboBox_pct_chg.setCurrentText("")
        self.comboBox_pct_chg.setObjectName("comboBox_pct_chg")
        self.gridLayout.addWidget(self.comboBox_pct_chg, 4, 1, 1, 1)
        self.lineEdit_stock_code_name = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_stock_code_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_stock_code_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_stock_code_name.setSizePolicy(sizePolicy)
        self.lineEdit_stock_code_name.setReadOnly(False)
        self.lineEdit_stock_code_name.setObjectName("lineEdit_stock_code_name")
        self.gridLayout.addWidget(self.lineEdit_stock_code_name, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label.setBaseSize(QtCore.QSize(30, 0))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_vol = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_vol.sizePolicy().hasHeightForWidth())
        self.comboBox_vol.setSizePolicy(sizePolicy)
        self.comboBox_vol.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_vol.setEditable(True)
        self.comboBox_vol.setCurrentText("")
        self.comboBox_vol.setObjectName("comboBox_vol")
        self.gridLayout.addWidget(self.comboBox_vol, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.comboBox_code = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_code.sizePolicy().hasHeightForWidth())
        self.comboBox_code.setSizePolicy(sizePolicy)
        self.comboBox_code.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_code.setEditable(True)
        self.comboBox_code.setCurrentText("")
        self.comboBox_code.setObjectName("comboBox_code")
        self.gridLayout.addWidget(self.comboBox_code, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_4.setBaseSize(QtCore.QSize(30, 0))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.lineEdit_turnover_rate = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_turnover_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_turnover_rate.setSizePolicy(sizePolicy)
        self.lineEdit_turnover_rate.setObjectName("lineEdit_turnover_rate")
        self.gridLayout.addWidget(self.lineEdit_turnover_rate, 6, 2, 1, 1)
        self.comboBox_turnover_rate = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_turnover_rate.sizePolicy().hasHeightForWidth())
        self.comboBox_turnover_rate.setSizePolicy(sizePolicy)
        self.comboBox_turnover_rate.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_turnover_rate.setEditable(True)
        self.comboBox_turnover_rate.setCurrentText("")
        self.comboBox_turnover_rate.setObjectName("comboBox_turnover_rate")
        self.gridLayout.addWidget(self.comboBox_turnover_rate, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.comboBox_pe = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pe.sizePolicy().hasHeightForWidth())
        self.comboBox_pe.setSizePolicy(sizePolicy)
        self.comboBox_pe.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_pe.setEditable(True)
        self.comboBox_pe.setCurrentText("")
        self.comboBox_pe.setObjectName("comboBox_pe")
        self.gridLayout.addWidget(self.comboBox_pe, 7, 1, 1, 1)
        self.lineEdit_pe = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pe.sizePolicy().hasHeightForWidth())
        self.lineEdit_pe.setSizePolicy(sizePolicy)
        self.lineEdit_pe.setObjectName("lineEdit_pe")
        self.gridLayout.addWidget(self.lineEdit_pe, 7, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_2)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.pushButton_dateselect = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_dateselect.setObjectName("pushButton_dateselect")
        self.verticalLayout_4.addWidget(self.pushButton_dateselect)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.pushButton_add_query_info = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_add_query_info.setObjectName("pushButton_add_query_info")
        self.verticalLayout_3.addWidget(self.pushButton_add_query_info)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_SQL = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_SQL.setObjectName("textEdit_SQL")
        self.horizontalLayout_3.addWidget(self.textEdit_SQL)
        self.pushButton_query = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_query.sizePolicy().hasHeightForWidth())
        self.pushButton_query.setSizePolicy(sizePolicy)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_3.addWidget(self.pushButton_query)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.tableView = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 100))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        UpsAndDownsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpsAndDownsWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_pct_chg.setCurrentIndex(-1)
        self.comboBox_vol.setCurrentIndex(-1)
        self.comboBox_code.setCurrentIndex(-1)
        self.comboBox_turnover_rate.setCurrentIndex(-1)
        self.comboBox_pe.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(UpsAndDownsWindow)

    def retranslateUi(self, UpsAndDownsWindow):
        _translate = QtCore.QCoreApplication.translate
        UpsAndDownsWindow.setWindowTitle(_translate("UpsAndDownsWindow", "涨跌分析"))
        self.groupBox_4.setTitle(_translate("UpsAndDownsWindow", "查询信息选择"))
        self.lineEdit_pct_chg.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.label_3.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>成交量单位：手</p></body></html>"))
        self.label_3.setText(_translate("UpsAndDownsWindow", "成交量"))
        self.lineEdit_vol.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.comboBox_pct_chg.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_stock_code_name.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.label.setText(_translate("UpsAndDownsWindow", "股票名称或代码"))
        self.comboBox_vol.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("UpsAndDownsWindow", "涨跌幅%"))
        self.comboBox_code.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("UpsAndDownsWindow", "换手率%"))
        self.lineEdit_turnover_rate.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.comboBox_turnover_rate.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("UpsAndDownsWindow", "市盈率%"))
        self.comboBox_pe.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_pe.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.pushButton_dateselect.setText(_translate("UpsAndDownsWindow", "删除选中日期信息"))
        self.pushButton_add_query_info.setText(_translate("UpsAndDownsWindow", "创建查询"))
        self.groupBox_2.setTitle(_translate("UpsAndDownsWindow", "SQL语句"))
        self.pushButton_query.setText(_translate("UpsAndDownsWindow", "开始查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UpsAndDownsWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UpsAndDownsWindow", "Tab 2"))

