# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\study\github\stockTushare\UI\upsdownsFm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpsAndDownsWindow(object):
    def setupUi(self, UpsAndDownsWindow):
        UpsAndDownsWindow.setObjectName("UpsAndDownsWindow")
        UpsAndDownsWindow.resize(762, 374)
        self.centralwidget = QtWidgets.QWidget(UpsAndDownsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label.setBaseSize(QtCore.QSize(30, 0))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit_stock_code_name = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_stock_code_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_stock_code_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_stock_code_name.setSizePolicy(sizePolicy)
        self.lineEdit_stock_code_name.setReadOnly(True)
        self.lineEdit_stock_code_name.setObjectName("lineEdit_stock_code_name")
        self.horizontalLayout.addWidget(self.lineEdit_stock_code_name)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_ptc_chg = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ptc_chg.sizePolicy().hasHeightForWidth())
        self.lineEdit_ptc_chg.setSizePolicy(sizePolicy)
        self.lineEdit_ptc_chg.setObjectName("lineEdit_ptc_chg")
        self.horizontalLayout.addWidget(self.lineEdit_ptc_chg)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vol.sizePolicy().hasHeightForWidth())
        self.lineEdit_vol.setSizePolicy(sizePolicy)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.horizontalLayout.addWidget(self.lineEdit_vol)
        self.pushButton_daily = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_daily.setObjectName("pushButton_daily")
        self.horizontalLayout.addWidget(self.pushButton_daily)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_4.setBaseSize(QtCore.QSize(30, 0))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_turnover_rate = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_turnover_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_turnover_rate.setSizePolicy(sizePolicy)
        self.lineEdit_turnover_rate.setObjectName("lineEdit_turnover_rate")
        self.horizontalLayout_4.addWidget(self.lineEdit_turnover_rate)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_pe = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pe.sizePolicy().hasHeightForWidth())
        self.lineEdit_pe.setSizePolicy(sizePolicy)
        self.lineEdit_pe.setObjectName("lineEdit_pe")
        self.horizontalLayout_4.addWidget(self.lineEdit_pe)
        self.pushButton_dailybasic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_dailybasic.setObjectName("pushButton_dailybasic")
        self.horizontalLayout_4.addWidget(self.pushButton_dailybasic)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_SQL = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_SQL.setObjectName("textEdit_SQL")
        self.horizontalLayout_3.addWidget(self.textEdit_SQL)
        self.pushButton_query = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_3.addWidget(self.pushButton_query)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_2)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.pushButton_dateselect = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_dateselect.setObjectName("pushButton_dateselect")
        self.verticalLayout_4.addWidget(self.pushButton_dateselect)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.tableView = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 100))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        UpsAndDownsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpsAndDownsWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(UpsAndDownsWindow)

    def retranslateUi(self, UpsAndDownsWindow):
        _translate = QtCore.QCoreApplication.translate
        UpsAndDownsWindow.setWindowTitle(_translate("UpsAndDownsWindow", "涨跌分析"))
        self.groupBox_4.setTitle(_translate("UpsAndDownsWindow", "日线行情信息选择"))
        self.label.setText(_translate("UpsAndDownsWindow", "股票名称或代码"))
        self.comboBox.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_stock_code_name.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.label_2.setText(_translate("UpsAndDownsWindow", "涨跌幅%"))
        self.lineEdit_ptc_chg.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.label_3.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>成交量单位：手</p></body></html>"))
        self.label_3.setText(_translate("UpsAndDownsWindow", "成交量"))
        self.lineEdit_vol.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.pushButton_daily.setText(_translate("UpsAndDownsWindow", "确定"))
        self.groupBox_3.setTitle(_translate("UpsAndDownsWindow", "每日指标信息选择"))
        self.label_4.setText(_translate("UpsAndDownsWindow", "换手率%"))
        self.lineEdit_turnover_rate.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.label_5.setText(_translate("UpsAndDownsWindow", "市盈率%"))
        self.lineEdit_pe.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.pushButton_dailybasic.setText(_translate("UpsAndDownsWindow", "确定"))
        self.groupBox_2.setTitle(_translate("UpsAndDownsWindow", "SQL语句"))
        self.pushButton_query.setText(_translate("UpsAndDownsWindow", "开始查询"))
        self.pushButton_dateselect.setText(_translate("UpsAndDownsWindow", "查询选中日期信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UpsAndDownsWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UpsAndDownsWindow", "Tab 2"))

