# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\study\github\stockTushare\UI\upsdownsFm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpsAndDownsWindow(object):
    def setupUi(self, UpsAndDownsWindow):
        UpsAndDownsWindow.setObjectName("UpsAndDownsWindow")
        UpsAndDownsWindow.resize(597, 617)
        self.centralwidget = QtWidgets.QWidget(UpsAndDownsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_daily = QtWidgets.QWidget()
        self.tab_daily.setObjectName("tab_daily")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_daily)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_daily)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_pct_chg = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pct_chg.sizePolicy().hasHeightForWidth())
        self.lineEdit_pct_chg.setSizePolicy(sizePolicy)
        self.lineEdit_pct_chg.setObjectName("lineEdit_pct_chg")
        self.gridLayout.addWidget(self.lineEdit_pct_chg, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vol.sizePolicy().hasHeightForWidth())
        self.lineEdit_vol.setSizePolicy(sizePolicy)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.gridLayout.addWidget(self.lineEdit_vol, 5, 2, 1, 1)
        self.comboBox_pct_chg = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pct_chg.sizePolicy().hasHeightForWidth())
        self.comboBox_pct_chg.setSizePolicy(sizePolicy)
        self.comboBox_pct_chg.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_pct_chg.setEditable(True)
        self.comboBox_pct_chg.setCurrentText("")
        self.comboBox_pct_chg.setObjectName("comboBox_pct_chg")
        self.gridLayout.addWidget(self.comboBox_pct_chg, 4, 1, 1, 1)
        self.lineEdit_daily_code = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_daily_code.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_daily_code.sizePolicy().hasHeightForWidth())
        self.lineEdit_daily_code.setSizePolicy(sizePolicy)
        self.lineEdit_daily_code.setReadOnly(False)
        self.lineEdit_daily_code.setObjectName("lineEdit_daily_code")
        self.gridLayout.addWidget(self.lineEdit_daily_code, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label.setBaseSize(QtCore.QSize(30, 0))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_vol = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_vol.sizePolicy().hasHeightForWidth())
        self.comboBox_vol.setSizePolicy(sizePolicy)
        self.comboBox_vol.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_vol.setEditable(True)
        self.comboBox_vol.setCurrentText("")
        self.comboBox_vol.setObjectName("comboBox_vol")
        self.gridLayout.addWidget(self.comboBox_vol, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.comboBox_daily_name = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_daily_name.sizePolicy().hasHeightForWidth())
        self.comboBox_daily_name.setSizePolicy(sizePolicy)
        self.comboBox_daily_name.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_daily_name.setEditable(True)
        self.comboBox_daily_name.setCurrentText("")
        self.comboBox_daily_name.setObjectName("comboBox_daily_name")
        self.gridLayout.addWidget(self.comboBox_daily_name, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_4.setBaseSize(QtCore.QSize(30, 0))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.lineEdit_turnover_rate = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_turnover_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_turnover_rate.setSizePolicy(sizePolicy)
        self.lineEdit_turnover_rate.setObjectName("lineEdit_turnover_rate")
        self.gridLayout.addWidget(self.lineEdit_turnover_rate, 6, 2, 1, 1)
        self.comboBox_turnover_rate = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_turnover_rate.sizePolicy().hasHeightForWidth())
        self.comboBox_turnover_rate.setSizePolicy(sizePolicy)
        self.comboBox_turnover_rate.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_turnover_rate.setEditable(True)
        self.comboBox_turnover_rate.setCurrentText("")
        self.comboBox_turnover_rate.setObjectName("comboBox_turnover_rate")
        self.gridLayout.addWidget(self.comboBox_turnover_rate, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.comboBox_pe = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pe.sizePolicy().hasHeightForWidth())
        self.comboBox_pe.setSizePolicy(sizePolicy)
        self.comboBox_pe.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_pe.setEditable(True)
        self.comboBox_pe.setCurrentText("")
        self.comboBox_pe.setObjectName("comboBox_pe")
        self.gridLayout.addWidget(self.comboBox_pe, 7, 1, 1, 1)
        self.lineEdit_pe = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pe.sizePolicy().hasHeightForWidth())
        self.lineEdit_pe.setSizePolicy(sizePolicy)
        self.lineEdit_pe.setObjectName("lineEdit_pe")
        self.gridLayout.addWidget(self.lineEdit_pe, 7, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_2)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.checkBox_daily_date_select = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_daily_date_select.setChecked(True)
        self.checkBox_daily_date_select.setObjectName("checkBox_daily_date_select")
        self.verticalLayout_4.addWidget(self.checkBox_daily_date_select)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.pushButton_add_query_info = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_add_query_info.setEnabled(True)
        self.pushButton_add_query_info.setObjectName("pushButton_add_query_info")
        self.verticalLayout_3.addWidget(self.pushButton_add_query_info)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_SQL = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_SQL.setObjectName("textEdit_SQL")
        self.horizontalLayout_3.addWidget(self.textEdit_SQL)
        self.pushButton_query = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_query.sizePolicy().hasHeightForWidth())
        self.pushButton_query.setSizePolicy(sizePolicy)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_3.addWidget(self.pushButton_query)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_daily, "")
        self.tab_top = QtWidgets.QWidget()
        self.tab_top.setObjectName("tab_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_top)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.tab_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_9.setBaseSize(QtCore.QSize(30, 0))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_top_amount_rate = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_amount_rate.sizePolicy().hasHeightForWidth())
        self.comboBox_top_amount_rate.setSizePolicy(sizePolicy)
        self.comboBox_top_amount_rate.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_amount_rate.setEditable(True)
        self.comboBox_top_amount_rate.setCurrentText("")
        self.comboBox_top_amount_rate.setObjectName("comboBox_top_amount_rate")
        self.gridLayout_2.addWidget(self.comboBox_top_amount_rate, 5, 1, 1, 1)
        self.comboBox_top_pct_change = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_pct_change.sizePolicy().hasHeightForWidth())
        self.comboBox_top_pct_change.setSizePolicy(sizePolicy)
        self.comboBox_top_pct_change.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_pct_change.setEditable(True)
        self.comboBox_top_pct_change.setCurrentText("")
        self.comboBox_top_pct_change.setObjectName("comboBox_top_pct_change")
        self.gridLayout_2.addWidget(self.comboBox_top_pct_change, 1, 1, 1, 1)
        self.lineEdit_top_code = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_top_code.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_code.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_code.setSizePolicy(sizePolicy)
        self.lineEdit_top_code.setReadOnly(False)
        self.lineEdit_top_code.setObjectName("lineEdit_top_code")
        self.gridLayout_2.addWidget(self.lineEdit_top_code, 0, 2, 1, 1)
        self.comboBox_top_turnover_rate = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_turnover_rate.sizePolicy().hasHeightForWidth())
        self.comboBox_top_turnover_rate.setSizePolicy(sizePolicy)
        self.comboBox_top_turnover_rate.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_turnover_rate.setEditable(True)
        self.comboBox_top_turnover_rate.setCurrentText("")
        self.comboBox_top_turnover_rate.setObjectName("comboBox_top_turnover_rate")
        self.gridLayout_2.addWidget(self.comboBox_top_turnover_rate, 2, 1, 1, 1)
        self.lineEdit_top_turnover_rate = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_turnover_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_turnover_rate.setSizePolicy(sizePolicy)
        self.lineEdit_top_turnover_rate.setObjectName("lineEdit_top_turnover_rate")
        self.gridLayout_2.addWidget(self.lineEdit_top_turnover_rate, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_7.setBaseSize(QtCore.QSize(30, 0))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_top_pct_change = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_pct_change.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_pct_change.setSizePolicy(sizePolicy)
        self.lineEdit_top_pct_change.setObjectName("lineEdit_top_pct_change")
        self.gridLayout_2.addWidget(self.lineEdit_top_pct_change, 1, 2, 1, 1)
        self.lineEdit_top_l_amount = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_l_amount.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_l_amount.setSizePolicy(sizePolicy)
        self.lineEdit_top_l_amount.setObjectName("lineEdit_top_l_amount")
        self.gridLayout_2.addWidget(self.lineEdit_top_l_amount, 3, 2, 1, 1)
        self.comboBox_top_name = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_top_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_name.sizePolicy().hasHeightForWidth())
        self.comboBox_top_name.setSizePolicy(sizePolicy)
        self.comboBox_top_name.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_name.setEditable(True)
        self.comboBox_top_name.setCurrentText("")
        self.comboBox_top_name.setObjectName("comboBox_top_name")
        self.gridLayout_2.addWidget(self.comboBox_top_name, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_top_net_amount = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_net_amount.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_net_amount.setSizePolicy(sizePolicy)
        self.lineEdit_top_net_amount.setObjectName("lineEdit_top_net_amount")
        self.gridLayout_2.addWidget(self.lineEdit_top_net_amount, 4, 2, 1, 1)
        self.comboBox_top_net_amount = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_net_amount.sizePolicy().hasHeightForWidth())
        self.comboBox_top_net_amount.setSizePolicy(sizePolicy)
        self.comboBox_top_net_amount.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_net_amount.setEditable(True)
        self.comboBox_top_net_amount.setCurrentText("")
        self.comboBox_top_net_amount.setObjectName("comboBox_top_net_amount")
        self.gridLayout_2.addWidget(self.comboBox_top_net_amount, 4, 1, 1, 1)
        self.comboBox_top_l_amount = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_top_l_amount.sizePolicy().hasHeightForWidth())
        self.comboBox_top_l_amount.setSizePolicy(sizePolicy)
        self.comboBox_top_l_amount.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_top_l_amount.setEditable(True)
        self.comboBox_top_l_amount.setCurrentText("")
        self.comboBox_top_l_amount.setObjectName("comboBox_top_l_amount")
        self.gridLayout_2.addWidget(self.comboBox_top_l_amount, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.lineEdit_top_amount_rate = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_top_amount_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_top_amount_rate.setSizePolicy(sizePolicy)
        self.lineEdit_top_amount_rate.setObjectName("lineEdit_top_amount_rate")
        self.gridLayout_2.addWidget(self.lineEdit_top_amount_rate, 5, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.calendarWidget_top = QtWidgets.QCalendarWidget(self.frame_6)
        self.calendarWidget_top.setGridVisible(True)
        self.calendarWidget_top.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget_top.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_top.setNavigationBarVisible(True)
        self.calendarWidget_top.setDateEditEnabled(True)
        self.calendarWidget_top.setObjectName("calendarWidget_top")
        self.verticalLayout_6.addWidget(self.calendarWidget_top)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.pushButton_add_top_query_info = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_add_top_query_info.setEnabled(True)
        self.pushButton_add_top_query_info.setObjectName("pushButton_add_top_query_info")
        self.verticalLayout_5.addWidget(self.pushButton_add_top_query_info)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_top_SQL = QtWidgets.QTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_top_SQL.sizePolicy().hasHeightForWidth())
        self.textEdit_top_SQL.setSizePolicy(sizePolicy)
        self.textEdit_top_SQL.setObjectName("textEdit_top_SQL")
        self.horizontalLayout_4.addWidget(self.textEdit_top_SQL)
        self.pushButton_top_query = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_top_query.sizePolicy().hasHeightForWidth())
        self.pushButton_top_query.setSizePolicy(sizePolicy)
        self.pushButton_top_query.setObjectName("pushButton_top_query")
        self.horizontalLayout_4.addWidget(self.pushButton_top_query)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_top, "")
        self.tab_moneyflow = QtWidgets.QWidget()
        self.tab_moneyflow.setObjectName("tab_moneyflow")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_moneyflow)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.tab_moneyflow)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_12.setBaseSize(QtCore.QSize(30, 0))
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.comboBox_moneyflow_name = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_moneyflow_name.sizePolicy().hasHeightForWidth())
        self.comboBox_moneyflow_name.setSizePolicy(sizePolicy)
        self.comboBox_moneyflow_name.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_moneyflow_name.setEditable(True)
        self.comboBox_moneyflow_name.setCurrentText("")
        self.comboBox_moneyflow_name.setObjectName("comboBox_moneyflow_name")
        self.horizontalLayout_6.addWidget(self.comboBox_moneyflow_name)
        self.lineEdit_moneyflow_code = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_moneyflow_code.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_moneyflow_code.sizePolicy().hasHeightForWidth())
        self.lineEdit_moneyflow_code.setSizePolicy(sizePolicy)
        self.lineEdit_moneyflow_code.setReadOnly(False)
        self.lineEdit_moneyflow_code.setObjectName("lineEdit_moneyflow_code")
        self.horizontalLayout_6.addWidget(self.lineEdit_moneyflow_code)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.calendarWidget_moneyflow = QtWidgets.QCalendarWidget(self.frame_7)
        self.calendarWidget_moneyflow.setGridVisible(True)
        self.calendarWidget_moneyflow.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget_moneyflow.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_moneyflow.setNavigationBarVisible(True)
        self.calendarWidget_moneyflow.setDateEditEnabled(True)
        self.calendarWidget_moneyflow.setObjectName("calendarWidget_moneyflow")
        self.verticalLayout_7.addWidget(self.calendarWidget_moneyflow)
        self.checkBox_moneyflow_date_select = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_moneyflow_date_select.setChecked(True)
        self.checkBox_moneyflow_date_select.setObjectName("checkBox_moneyflow_date_select")
        self.verticalLayout_7.addWidget(self.checkBox_moneyflow_date_select)
        self.pushButton_add_moneyflow_query = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_add_moneyflow_query.setEnabled(True)
        self.pushButton_add_moneyflow_query.setObjectName("pushButton_add_moneyflow_query")
        self.verticalLayout_7.addWidget(self.pushButton_add_moneyflow_query)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_moneyflow)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.textEdit_moneyflow_SQL = QtWidgets.QTextEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_moneyflow_SQL.sizePolicy().hasHeightForWidth())
        self.textEdit_moneyflow_SQL.setSizePolicy(sizePolicy)
        self.textEdit_moneyflow_SQL.setObjectName("textEdit_moneyflow_SQL")
        self.horizontalLayout_7.addWidget(self.textEdit_moneyflow_SQL)
        self.pushButton_moneyflow_query = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_moneyflow_query.sizePolicy().hasHeightForWidth())
        self.pushButton_moneyflow_query.setSizePolicy(sizePolicy)
        self.pushButton_moneyflow_query.setObjectName("pushButton_moneyflow_query")
        self.horizontalLayout_7.addWidget(self.pushButton_moneyflow_query)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_moneyflow, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.checkBox_high_light_net_positive = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_high_light_net_positive.setObjectName("checkBox_high_light_net_positive")
        self.verticalLayout.addWidget(self.checkBox_high_light_net_positive)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 200))
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        UpsAndDownsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpsAndDownsWindow)
        self.tabWidget.setCurrentIndex(2)
        self.comboBox_pct_chg.setCurrentIndex(-1)
        self.comboBox_vol.setCurrentIndex(-1)
        self.comboBox_daily_name.setCurrentIndex(-1)
        self.comboBox_turnover_rate.setCurrentIndex(-1)
        self.comboBox_pe.setCurrentIndex(-1)
        self.comboBox_top_amount_rate.setCurrentIndex(-1)
        self.comboBox_top_pct_change.setCurrentIndex(-1)
        self.comboBox_top_turnover_rate.setCurrentIndex(-1)
        self.comboBox_top_name.setCurrentIndex(-1)
        self.comboBox_top_net_amount.setCurrentIndex(-1)
        self.comboBox_top_l_amount.setCurrentIndex(-1)
        self.comboBox_moneyflow_name.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(UpsAndDownsWindow)

    def retranslateUi(self, UpsAndDownsWindow):
        _translate = QtCore.QCoreApplication.translate
        UpsAndDownsWindow.setWindowTitle(_translate("UpsAndDownsWindow", "涨跌分析"))
        self.groupBox_4.setTitle(_translate("UpsAndDownsWindow", "查询信息选择"))
        self.lineEdit_pct_chg.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.label_3.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>成交量单位：手</p></body></html>"))
        self.label_3.setText(_translate("UpsAndDownsWindow", "成交量"))
        self.lineEdit_vol.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.comboBox_pct_chg.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_daily_code.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.label.setText(_translate("UpsAndDownsWindow", "股票名称或代码"))
        self.comboBox_vol.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("UpsAndDownsWindow", "涨跌幅%"))
        self.comboBox_daily_name.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("UpsAndDownsWindow", "换手率%"))
        self.lineEdit_turnover_rate.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.comboBox_turnover_rate.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("UpsAndDownsWindow", "市盈率%"))
        self.comboBox_pe.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_pe.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.checkBox_daily_date_select.setText(_translate("UpsAndDownsWindow", "添加时间查询"))
        self.pushButton_add_query_info.setText(_translate("UpsAndDownsWindow", "创建查询"))
        self.groupBox_2.setTitle(_translate("UpsAndDownsWindow", "SQL语句"))
        self.pushButton_query.setText(_translate("UpsAndDownsWindow", "开始查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_daily), _translate("UpsAndDownsWindow", "交易信息查询"))
        self.groupBox_5.setTitle(_translate("UpsAndDownsWindow", "查询信息选择"))
        self.label_9.setText(_translate("UpsAndDownsWindow", "换手率%"))
        self.comboBox_top_amount_rate.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.comboBox_top_pct_change.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_top_code.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>目前在龙虎榜处无意义，先保留</p></body></html>"))
        self.comboBox_top_turnover_rate.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_top_turnover_rate.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入换手率，必须为数字，一般为正</p></body></html>"))
        self.label_8.setText(_translate("UpsAndDownsWindow", "涨跌幅%"))
        self.label_7.setText(_translate("UpsAndDownsWindow", "股票名称或代码"))
        self.lineEdit_top_pct_change.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.lineEdit_top_l_amount.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>单位：元</p></body></html>"))
        self.comboBox_top_name.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_10.setText(_translate("UpsAndDownsWindow", "龙虎榜净买入额"))
        self.lineEdit_top_net_amount.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>净买入额，单位为元</p></body></html>"))
        self.comboBox_top_net_amount.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.comboBox_top_l_amount.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.label_6.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>成交量单位：手</p></body></html>"))
        self.label_6.setText(_translate("UpsAndDownsWindow", "龙虎榜成交额"))
        self.label_11.setText(_translate("UpsAndDownsWindow", "龙虎榜成交额占比"))
        self.lineEdit_top_amount_rate.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>输入涨跌幅，可以正可以负</p></body></html>"))
        self.pushButton_add_top_query_info.setText(_translate("UpsAndDownsWindow", "创建查询"))
        self.groupBox_3.setTitle(_translate("UpsAndDownsWindow", "SQL语句"))
        self.pushButton_top_query.setText(_translate("UpsAndDownsWindow", "开始查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_top), _translate("UpsAndDownsWindow", "龙虎榜查询"))
        self.label_12.setText(_translate("UpsAndDownsWindow", "股票名称或代码"))
        self.comboBox_moneyflow_name.setWhatsThis(_translate("UpsAndDownsWindow", "<html><head/><body><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p><br/></p></body></html>"))
        self.lineEdit_moneyflow_code.setToolTip(_translate("UpsAndDownsWindow", "<html><head/><body><p>请输入完整的股票代码或者股票名称</p></body></html>"))
        self.checkBox_moneyflow_date_select.setText(_translate("UpsAndDownsWindow", "添加时间查询"))
        self.pushButton_add_moneyflow_query.setText(_translate("UpsAndDownsWindow", "创建查询"))
        self.groupBox_6.setTitle(_translate("UpsAndDownsWindow", "SQL语句"))
        self.pushButton_moneyflow_query.setText(_translate("UpsAndDownsWindow", "开始查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_moneyflow), _translate("UpsAndDownsWindow", "资金流向"))
        self.checkBox_high_light_net_positive.setText(_translate("UpsAndDownsWindow", "高亮显示超大单和大单买净买入为正的数据"))

